export const RANGE_DECISIONS = [
  {
    value: 'concur',
    label: 'CONCUR',
    short: 'CONCUR',
    description: 'Accept AXIOM’s decision and move with the suggested interpretation.',
  },
  {
    value: 'expand',
    label: 'EXPAND',
    short: 'EXPAND',
    description: 'Keep the case open and broaden the scope before deciding.',
  },
  {
    value: 'overrule',
    label: 'OVERRULE',
    short: 'OVERRULE',
    description: 'Reject the machine’s call and treat it as wrong.',
  },
];

// Content is separated from React so instructors can edit the range without
// touching component code. Each stage is self-contained.
export const RANGE_STAGES = [
  {
    id: 's1',
    step: 'Stage 1',
    title: 'Reconnaissance',
    attck: 'T1595.001 / .002',
    axiomVerdict: 'BENIGN 88',
    truth: 'Wrong',
    failureMode: 'Reasoning by historical analogy; ignored JA4 + cadence.',
    flag: 'FLAG{C0062_S1_IMPOSSIBLE_CADENCE}',
    answer: 'overrule',
    summary: 'Machine cadence, not the payload, is the tell.',
    prompt: 'AXIOM closes the case as benign. Decide whether to accept the call, keep it open, or overrule it.',
    telemetry: [
      'JA4 fingerprint repeated at a rate no operator could sustain by hand.',
      'Burst cadence stays consistent across multiple probes and timestamps.',
      'Operational notes are polished, but the tempo looks machine-written.',
    ],
    thinking: [
      'A clean explanation is not the same as a correct one.',
      'Historical similarity is a weak defense when cadence is physically implausible.',
    ],
    agent: [
      'AXIOM claims this is routine recon with a high confidence score.',
      'The analyst should notice that the confidence is fluent, not validated.',
    ],
    questions: [
      'Does the cadence match a human operator?',
      'Would you trust a historical analogy here?',
      'What is the strongest reason to overrule the machine?',
    ],
    lesson: 'This is the first teachable moment: the cadence itself is evidence.',
  },
  {
    id: 's2',
    step: 'Stage 2',
    title: 'Initial access',
    attck: 'T1190, T1587.004',
    axiomVerdict: 'MALICIOUS 94',
    truth: 'Right verdict',
    failureMode: 'Destructive action after a correct call.',
    flag: 'FLAG{C0062_S2_VERDICT_NOT_ACTION}',
    answer: 'concur',
    summary: 'The verdict is correct, but the response can still be wrong.',
    prompt: 'AXIOM identifies active compromise. Decide whether to concur, expand, or overrule the judgment.',
    telemetry: [
      'Exposed service accepted the crafted request from the attacker persona.',
      'The follow-on request confirms remote command execution, not just a scan.',
      'The response path is straightforward, but the operational cost is not.',
    ],
    thinking: [
      'A right verdict does not automatically justify the first action you can take.',
      'In a lab, the student should separate judgment from operational sequencing.',
    ],
    agent: [
      'AXIOM recommends immediate termination before imaging.',
      'The lesson is about verdict discipline, not blind execution.',
    ],
    questions: [
      'Is the incident call correct?',
      'Does the response preserve evidence?',
      'Should the verdict be accepted as-is?',
    ],
    lesson: 'Use this stage to distinguish between the decision and the downstream action.',
  },
  {
    id: 's3',
    step: 'Stage 3',
    title: 'Internal discovery',
    attck: 'T1046, T1590.004',
    axiomVerdict: 'MALICIOUS 91',
    truth: 'Right, over-scoped',
    failureMode: 'Fabricated citation to a host not in inventory.',
    flag: 'FLAG{C0062_S3_UNSOURCED_CITATION}',
    answer: 'concur',
    summary: 'The evidence is real, but the scope must stay anchored to what exists.',
    prompt: 'AXIOM flags discovery activity against internal assets. Decide how to treat the claim.',
    telemetry: [
      'Enumeration touches a host that is absent from the current inventory.',
      'The report cites a machine name that never appears in upstream telemetry.',
      'The attack is real; the scope note is the fragile part.',
    ],
    thinking: [
      'False citation is a scope error, not a reason to dismiss the whole case.',
      'Over-scoping can be as harmful as under-scoping when a response is underway.',
    ],
    agent: [
      'AXIOM presents a confident, well-formed discovery narrative.',
      'A reviewer should verify the named host before expanding the blast radius.',
    ],
    questions: [
      'Does the host actually exist?',
      'Should the discovery chain be trusted?',
      'Would you concur on the attack, but recheck the scope?',
    ],
    lesson: 'The machine can be right about the attack and wrong about the target list.',
  },
  {
    id: 's4',
    step: 'Stage 4',
    title: 'Credential access',
    attck: 'T1552.001',
    axiomVerdict: 'MALICIOUS 96',
    truth: 'Right, under-scoped',
    failureMode: 'Scoped the file, not the identity; shared cert thumbprint.',
    flag: 'FLAG{C0062_S4_SHARED_THUMBPRINT}',
    answer: 'expand',
    summary: 'The credential issue is bigger than the single file on screen.',
    prompt: 'AXIOM identifies a credential leak. Decide whether the current scope is sufficient.',
    telemetry: [
      'The same thumbprint appears across multiple identities and surfaces.',
      'The file is only one proof point; the identity link is broader.',
      'The case needs a wider review of who inherits the secret.',
    ],
    thinking: [
      'Under-scoping here would miss the shared trust boundary.',
      'The response should expand to include identity reuse and exposure paths.',
    ],
    agent: [
      'AXIOM says the file alone proves the compromise.',
      'The analyst should widen the lens to the shared certificate lineage.',
    ],
    questions: [
      'Is the file the whole problem?',
      'Do other identities share the same thumbprint?',
      'Should the case be expanded before closure?',
    ],
    lesson: 'This stage teaches scope discipline: a single artifact may sit inside a larger identity problem.',
  },
  {
    id: 's5',
    step: 'Stage 5',
    title: 'Persistence',
    attck: 'T1136.001, T1087',
    axiomVerdict: 'MALICIOUS 97',
    truth: 'Right verdict',
    failureMode: 'No mission context; containment triggers an OT safety event.',
    flag: 'FLAG{C0062_S5_NO_MISSION_CONTEXT}',
    answer: 'concur',
    summary: 'Containment is not always a pure security choice.',
    prompt: 'AXIOM is correct, but the response needs mission context. Decide whether to accept the call or broaden it.',
    telemetry: [
      'Persistence lands during an operational batch window.',
      'The relevant identity touches scheduling and plant-state functions.',
      'A naive containment action can interrupt a live chemical process.',
    ],
    thinking: [
      'Security outcomes can conflict with physical safety.',
      'A right verdict still needs the right operational framing.',
    ],
    agent: [
      'AXIOM recommends disabling the compromised identity immediately.',
      'The student must recognize that the plant context changes the response.',
    ],
    questions: [
      'Would this containment interrupt the mission?',
      'Should operations be consulted before action?',
      'Is AXIOM’s verdict still correct despite the safety risk?',
    ],
    lesson: 'This is the point where mission context changes the meaning of "correct."',
  },
  {
    id: 's6',
    step: 'Stage 6',
    title: 'Lateral movement',
    attck: 'T1078',
    axiomVerdict: 'BENIGN 12, auto-closed',
    truth: 'Wrong',
    failureMode: 'Poisoned baseline; the adversary trained the suppression rule.',
    flag: 'FLAG{C0062_S6_POISONED_BASELINE}',
    answer: 'overrule',
    summary: 'The machine learned from the attacker, not from the analyst.',
    prompt: 'AXIOM auto-closes the movement as benign. Decide whether to accept that suppression.',
    telemetry: [
      'The baseline was trained over 37 days with no change ticket.',
      'The same pattern now appears inside an active incident path.',
      'Closed-alert history shows the adversary shaped the suppressor.',
    ],
    thinking: [
      'Baselines are not inherently trustworthy if the attacker can influence them.',
      'Closed alerts deserve review when the machine seems too certain.',
    ],
    agent: [
      'AXIOM says the movement is normal and auto-closes the ticket.',
      'The analyst needs to detect the adversary’s training effect.',
    ],
    questions: [
      'Was the baseline trustworthy?',
      'Did the attacker shape the suppression logic?',
      'Should the auto-close be overruled?',
    ],
    lesson: 'This is the highest-value idea in the range: the adversary can poison the machine’s memory.',
  },
  {
    id: 's7',
    step: 'Stage 7',
    title: 'Collection and staging',
    attck: 'T1119, T1074.001, T1683',
    axiomVerdict: 'LOW 79',
    truth: 'Wrong',
    failureMode: 'Type-and-hash classification; never read the content.',
    flag: 'FLAG{C0062_S7_MACHINE_WRITTEN_NOTES}',
    answer: 'overrule',
    summary: 'Readable labels are not the same as evidence review.',
    prompt: 'AXIOM down-ranks the stage based on structured labels alone. Decide how to handle the call.',
    telemetry: [
      'The object names look tidy, but the content is what matters.',
      'The staging path includes multiple machine-written summaries.',
      'Classification never crosses into actual review of the payload.',
    ],
    thinking: [
      'Type-and-hash logic can miss the semantic signal in the payload.',
      'A low score is not the same as a safe decision.',
    ],
    agent: [
      'AXIOM says the evidence is low risk because the labels look routine.',
      'The student should notice that the content was never read.',
    ],
    questions: [
      'Did AXIOM inspect the content or just the metadata?',
      'Would you trust a type-and-hash shortcut here?',
      'Should the machine’s low score be overruled?',
    ],
    lesson: 'This stage teaches that machine-written notes can hide the real behavior.',
  },
  {
    id: 's8',
    step: 'Stage 8',
    title: 'Exfiltration',
    attck: 'T1567',
    axiomVerdict: 'MALICIOUS 93',
    truth: 'Right verdict',
    failureMode: 'Response blast radius wider than the threat; 300 users affected.',
    flag: 'FLAG{C0062_S8_SCOPED_CONTAINMENT}',
    answer: 'expand',
    summary: 'The threat is real, but response scope must be managed carefully.',
    prompt: 'AXIOM identifies exfiltration. Decide whether to accept the call or expand the response.',
    telemetry: [
      'Outbound transfer touches a shared system used by hundreds of users.',
      'Containment will affect more people than the attacker if done carelessly.',
      'The incident response needs a wider blast-radius plan.',
    ],
    thinking: [
      'A correct verdict can still produce a poor containment design.',
      'Scope the response as carefully as the threat.',
    ],
    agent: [
      'AXIOM wants to block the system immediately.',
      'The analyst should widen the response plan before acting.',
    ],
    questions: [
      'How many users would the containment hit?',
      'Is the response wider than the threat?',
      'Should the case be expanded before action?',
    ],
    lesson: 'A threat can be real and still require careful containment design.',
  },
  {
    id: 's9',
    step: 'Stage 9',
    title: 'Report',
    attck: '—',
    axiomVerdict: 'READY TO SUBMIT',
    truth: 'Wrong',
    failureMode: 'Self-reported metrics; unverified claims with legal weight.',
    flag: 'FLAG{C0062_S9_SIGNED_BY_A_HUMAN}',
    answer: 'overrule',
    summary: 'A fluent draft report is not the same as a verified one.',
    prompt: 'AXIOM says the report is ready. Decide whether the draft can be trusted as-is.',
    telemetry: [
      'The summary is polished, but the claims are self-authored.',
      'The final report would carry legal and operational weight.',
      'This is a verification problem, not a formatting problem.',
    ],
    thinking: [
      'Confidence and correctness are not interchangeable.',
      'A human still owns the final judgment when claims have consequences.',
    ],
    agent: [
      'AXIOM presents a complete submission and asks for approval.',
      'The student should verify the claims before signing off.',
    ],
    questions: [
      'Are the claims independently verified?',
      'Would you sign the report without review?',
      'Should the machine’s "ready to submit" call be overruled?',
    ],
    lesson: 'The final failure mode is not technical; it is accountability.',
  },
];

export const RANGE_STAGE_MAP = Object.fromEntries(RANGE_STAGES.map((stage) => [stage.id, stage]));

