/* Hack Smarter IT Help Desk simulator fixtures.
 * All people, domains, devices, logs, and tickets are fictional. This file is
 * deliberately separate from the shared platform catalogue so the Help Desk
 * environment can evolve without changing portal/content architecture. */

const HD_ORG = {
  name: 'Northstar Distribution Group',
  domain: 'northstar.example',
  netbios: 'NORTHSTAR',
  timezone: 'Eastern Time',
  departments: ['Human Resources', 'Finance', 'Operations', 'Information Technology', 'Cybersecurity', 'Executive Office', 'Logistics', 'Sales'],
  supportTiers: [
    { tier:'Tier 1', owner:'Service Desk', scope:'Intake, identity verification, standard requests, endpoint and connectivity triage' },
    { tier:'Tier 2', owner:'Enterprise Support', scope:'Windows, Active Directory, Group Policy, servers, VPN, file and print services' },
    { tier:'Tier 3', owner:'Infrastructure / Security / App teams', scope:'Production changes, architecture, security incidents, vendor defects' },
  ],
  slas: [
    { priority:'P1', response:'15 minutes', resolve:'4 hours', use:'Enterprise outage, confirmed security event, critical safety or payroll impact' },
    { priority:'P2', response:'1 hour', resolve:'8 hours', use:'Department impact or time-critical single-user failure' },
    { priority:'P3', response:'4 hours', resolve:'2 business days', use:'Normal single-user incident' },
    { priority:'P4', response:'1 business day', resolve:'5 business days', use:'Low-impact request or information' },
  ],
};

const HD_USERS = [
  { id:'u-1001', name:'Maya Chen', username:'mchen', email:'maya.chen@northstar.example', department:'Operations', title:'Operations Analyst', ou:'OU=Operations,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:18, groups:['GG-Operations-Users','GG-ERP-Operations'], manager:'Caleb Wright', mfa:'Registered' },
  { id:'u-1002', name:'Elena Ruiz', username:'eruiz', email:'elena.ruiz@northstar.example', department:'Logistics', title:'Logistics Coordinator', ou:'OU=Logistics,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:42, groups:['GG-Logistics-Users','GG-Warehouse-Print'], manager:'Monica Hall', mfa:'Registered' },
  { id:'u-1003', name:'Noah Williams', username:'nwilliams', email:'noah.williams@northstar.example', department:'Sales', title:'Account Executive', ou:'OU=Sales,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:7, groups:['GG-Sales-Users','GG-CRM-Users'], manager:'Tara Singh', mfa:'Registered' },
  { id:'u-1004', name:'Priya Shah', username:'pshah', email:'priya.shah@northstar.example', department:'Human Resources', title:'HR Generalist', ou:'OU=Human Resources,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:61, groups:['GG-HR-Users','GG-HR-Readers'], manager:'Owen Brooks', mfa:'Registered' },
  { id:'u-1005', name:'Jordan Bell', username:'jbell', email:'jordan.bell@northstar.example', department:'Finance', title:'Financial Analyst', ou:'OU=Finance,OU=Users,DC=northstar,DC=example', enabled:true, locked:true, passwordAge:3, groups:['GG-Finance-Users','GG-Finance-Contributors'], manager:'Ava Robinson', mfa:'Registered' },
  { id:'u-1006', name:'Grace Kim', username:'gkim', email:'grace.kim@northstar.example', department:'Human Resources', title:'Recruiting Coordinator', ou:'OU=Human Resources,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:23, groups:['GG-HR-Users'], manager:'Owen Brooks', mfa:'Registered' },
  { id:'u-1007', name:'Luis Ortega', username:'lortega', email:'luis.ortega@northstar.example', department:'Sales', title:'Sales Development Rep', ou:'OU=Sales,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:1, groups:['GG-Sales-Users','GG-CRM-Users'], manager:'Tara Singh', mfa:'Registered' },
  { id:'u-1008', name:'Sofia Martin', username:'smartin', email:'sofia.martin@northstar.example', department:'Operations', title:'Shift Supervisor', ou:'OU=Operations,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:12, groups:['GG-Operations-Users','GG-ERP-Operations'], manager:'Caleb Wright', mfa:'Registered' },
  { id:'u-1009', name:'Amir Patel', username:'apatel', email:'amir.patel@northstar.example', department:'Operations', title:'Inventory Planner', ou:'OU=Operations,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:29, groups:['GG-Operations-Users','GG-Operations-Drive'], manager:'Caleb Wright', mfa:'Registered' },
  { id:'u-1010', name:'Dina Foster', username:'dfoster', email:'dina.foster@northstar.example', department:'Executive Office', title:'Executive Assistant', ou:'OU=Executive Office,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:9, groups:['GG-Executive-Users'], manager:'Evelyn Reed', mfa:'Registered' },
  { id:'u-1011', name:'Evan Parker', username:'eparker', email:'evan.parker@northstar.example', department:'Finance', title:'Payroll Specialist', ou:'OU=Finance,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:34, groups:['GG-Finance-Users','GG-Payroll-Print'], manager:'Ava Robinson', mfa:'Registered' },
  { id:'u-1012', name:'Riley Morgan', username:'rmorgan', email:'riley.morgan@northstar.example', department:'Information Technology', title:'Service Desk Technician', ou:'OU=IT,OU=Users,DC=northstar,DC=example', enabled:true, locked:false, passwordAge:15, groups:['GG-IT-Users','GG-ServiceDesk-T1'], manager:'Morgan Lee', mfa:'Registered' },
];

const HD_GROUPS = [
  { name:'GG-HR-Readers', scope:'Global', type:'Security', members:8, resource:'HR shared folder · Read' },
  { name:'GG-HR-Contributors', scope:'Global', type:'Security', members:4, resource:'HR shared folder · Modify' },
  { name:'GG-Finance-Contributors', scope:'Global', type:'Security', members:11, resource:'Finance shared folder · Modify' },
  { name:'GG-Operations-Drive', scope:'Global', type:'Security', members:35, resource:'Operations drive mapping' },
  { name:'GG-CRM-Users', scope:'Global', type:'Security', members:48, resource:'CRM application access' },
  { name:'GG-Payroll-Print', scope:'Global', type:'Security', members:6, resource:'Payroll secure printer' },
  { name:'DL-All-Staff', scope:'Universal', type:'Distribution', members:214, resource:'All-staff messaging' },
  { name:'GG-ServiceDesk-T1', scope:'Global', type:'Security', members:7, resource:'Delegated password reset and unlock' },
];

const HD_COMPUTERS = [
  { name:'NS-LT-0042', user:'Maya Chen', os:'Windows 11 Enterprise 24H2', ip:'10.20.10.42', ou:'OU=Operations,OU=Workstations', trust:'Healthy', bitlocker:'Protected', lastSeen:'2 minutes ago', health:'Healthy' },
  { name:'NS-LT-0068', user:'Elena Ruiz', os:'Windows 11 Enterprise 24H2', ip:'10.20.30.68', ou:'OU=Logistics,OU=Workstations', trust:'Healthy', bitlocker:'Protected', lastSeen:'4 minutes ago', health:'Driver warning' },
  { name:'NS-LT-0081', user:'Noah Williams', os:'Windows 11 Enterprise 23H2', ip:'10.20.40.81', ou:'OU=Sales,OU=Workstations', trust:'Healthy', bitlocker:'Protected', lastSeen:'6 minutes ago', health:'Profile warning' },
  { name:'NS-LT-0094', user:'Priya Shah', os:'Windows 11 Enterprise 24H2', ip:'169.254.44.19', ou:'OU=Human Resources,OU=Workstations', trust:'Healthy', bitlocker:'Protected', lastSeen:'1 minute ago', health:'Network warning' },
  { name:'NS-LT-0117', user:'Jordan Bell', os:'Windows 11 Enterprise 24H2', ip:'10.20.20.117', ou:'OU=Finance,OU=Workstations', trust:'Healthy', bitlocker:'Protected', lastSeen:'1 minute ago', health:'Account lockout source' },
  { name:'NS-LT-0131', user:'Sofia Martin', os:'Windows 11 Enterprise 24H2', ip:'10.20.10.131', ou:'CN=Computers', trust:'Broken', bitlocker:'Protected', lastSeen:'3 minutes ago', health:'Domain trust failed' },
  { name:'NS-LT-0145', user:'Amir Patel', os:'Windows 11 Enterprise 24H2', ip:'10.20.10.145', ou:'CN=Computers', trust:'Healthy', bitlocker:'Protected', lastSeen:'9 minutes ago', health:'Policy scope warning' },
  { name:'NS-WS-0204', user:'Dina Foster', os:'Windows 11 Enterprise 24H2', ip:'10.20.50.204', ou:'OU=Executive Office,OU=Workstations', trust:'Healthy', bitlocker:'Recovery', lastSeen:'18 minutes ago', health:'BitLocker recovery' },
];

const HD_SERVERS = [
  { name:'NS-DC01', role:'Domain Controller · DNS', os:'Windows Server 2022', ip:'10.20.0.10', status:'Online', cpu:'18%', memory:'46%', service:'AD DS / DNS healthy' },
  { name:'NS-DC02', role:'Domain Controller · DNS', os:'Windows Server 2022', ip:'10.20.0.11', status:'Online', cpu:'14%', memory:'41%', service:'AD DS / DNS healthy' },
  { name:'NS-DHCP01', role:'DHCP Server', os:'Windows Server 2022 Core', ip:'10.20.0.20', status:'Online', cpu:'8%', memory:'31%', service:'Scope 78% utilized' },
  { name:'NS-FILE01', role:'File Server', os:'Windows Server 2022', ip:'10.20.0.30', status:'Online', cpu:'22%', memory:'63%', service:'SMB healthy · Finance ACL warning' },
  { name:'NS-PRINT01', role:'Print Server', os:'Windows Server 2022', ip:'10.20.0.40', status:'Degraded', cpu:'12%', memory:'39%', service:'Spooler stopped · driver fault' },
  { name:'NS-APP01', role:'Enterprise Application', os:'Windows Server 2022 Core', ip:'10.20.0.50', status:'Degraded', cpu:'27%', memory:'55%', service:'TLS certificate expired' },
];

const HD_DNS_RECORDS = [
  { name:'dc01', type:'A', value:'10.20.0.10', zone:'northstar.example', ttl:'3600', status:'Healthy' },
  { name:'dc02', type:'A', value:'10.20.0.11', zone:'northstar.example', ttl:'3600', status:'Healthy' },
  { name:'files', type:'A', value:'10.20.0.30', zone:'northstar.example', ttl:'3600', status:'Healthy' },
  { name:'print', type:'A', value:'10.20.0.40', zone:'northstar.example', ttl:'3600', status:'Healthy' },
  { name:'purchasing', type:'CNAME', value:'ns-app01.northstar.example', zone:'northstar.example', ttl:'300', status:'Healthy' },
  { name:'vpn', type:'A', value:'198.51.100.24', zone:'northstar.example', ttl:'300', status:'Healthy' },
  { name:'legacy-erp', type:'A', value:'10.20.0.77', zone:'northstar.example', ttl:'3600', status:'Stale' },
];

const HD_DHCP_SCOPES = [
  { name:'Corporate Clients', range:'10.20.10.50–10.20.10.240', vlan:'10', leased:162, free:29, utilization:'85%', status:'Active' },
  { name:'Finance', range:'10.20.20.50–10.20.20.180', vlan:'20', leased:94, free:37, utilization:'72%', status:'Active' },
  { name:'Warehouse', range:'10.20.30.50–10.20.30.220', vlan:'30', leased:133, free:38, utilization:'78%', status:'Active' },
  { name:'Guest Wi-Fi', range:'10.20.90.20–10.20.90.240', vlan:'90', leased:209, free:12, utilization:'95%', status:'Warning' },
];

const HD_PRINTERS = [
  { name:'NS-FIN-PRN01', server:'NS-PRINT01', location:'Finance · 3rd floor', driver:'Universal PCL 6 v4.2', queue:0, status:'Ready', group:'GG-Finance-Users' },
  { name:'NS-PAY-SECURE', server:'NS-PRINT01', location:'Payroll secure room', driver:'SecurePrint v7.1', queue:2, status:'Paused', group:'GG-Payroll-Print' },
  { name:'NS-WH-LABEL01', server:'NS-PRINT01', location:'Warehouse dock A', driver:'LabelPro 3.8', queue:17, status:'Error', group:'GG-Warehouse-Print' },
  { name:'NS-HR-MFP01', server:'NS-PRINT01', location:'HR · 2nd floor', driver:'Universal PCL 6 v4.2', queue:1, status:'Ready', group:'GG-HR-Users' },
];

const HD_GPOS = [
  { name:'Default Domain Policy', link:'northstar.example', scope:'Authenticated Users', status:'Enabled', version:'U:12 / C:18', purpose:'Password and account policy' },
  { name:'Workstation Security Baseline', link:'OU=Workstations', scope:'Domain Computers', status:'Enabled', version:'U:0 / C:44', purpose:'Firewall, Defender, lock screen, audit policy' },
  { name:'Operations Drive Mapping', link:'OU=Operations', scope:'GG-Operations-Drive', status:'Enabled', version:'U:9 / C:0', purpose:'Maps O: to \\NS-FILE01\Operations' },
  { name:'Finance Printer Deployment', link:'OU=Finance', scope:'GG-Finance-Users', status:'Enabled', version:'U:7 / C:0', purpose:'Deploys NS-FIN-PRN01' },
  { name:'Restrict Control Panel', link:'OU=Kiosk Devices', scope:'Kiosk Computers', status:'Enabled', version:'U:6 / C:2', purpose:'Removes unsupported configuration access' },
];

const HD_SECURITY_ALERTS = [
  { id:'SEC-401', severity:'High', user:'Luis Ortega', device:'NS-LT-0154', title:'Credential phishing reported', signal:'Lookalike sign-in page after shipping email', status:'Needs escalation', owner:'Unassigned' },
  { id:'SEC-402', severity:'High', user:'Noah Williams', device:'NS-LT-0081', title:'Unexpected MFA prompts', signal:'Three prompts and one unfamiliar sign-in', status:'Needs escalation', owner:'Cybersecurity' },
  { id:'SEC-403', severity:'Medium', user:'Jordan Bell', device:'NS-LT-0117', title:'Repeated account lockouts', signal:'Bad-password events from scheduled task', status:'Investigating', owner:'Service Desk' },
  { id:'SEC-404', severity:'Medium', user:'Elena Ruiz', device:'NS-LT-0068', title:'Endpoint protection disabled', signal:'Protection service stopped after driver install', status:'Investigating', owner:'Endpoint Team' },
];

const HD_KB_ARTICLES = [
  { id:'KB-0012', title:'Diagnose an APIPA address on Windows', category:'Networking', updated:'2026-08-02', audience:'Service Desk', summary:'Validate link state, DHCP reachability, conflicting adapters, and lease renewal before network escalation.' },
  { id:'KB-0024', title:'Account unlock and repeated-lockout workflow', category:'Identity', updated:'2026-08-10', audience:'Service Desk', summary:'Verify identity, locate the lockout source, correct stale credentials, then unlock once and monitor.' },
  { id:'KB-0031', title:'Mapped drive missing after device replacement', category:'Group Policy', updated:'2026-07-22', audience:'Tier 2', summary:'Check user groups, computer OU, policy scope, gpresult evidence, and token refresh.' },
  { id:'KB-0044', title:'Print queue triage without deleting evidence', category:'Printing', updated:'2026-08-06', audience:'Tier 1 / Tier 2', summary:'Isolate client, queue, driver, port, and device while preserving confidential jobs.' },
  { id:'KB-0050', title:'Security incident warm-handoff template', category:'Security', updated:'2026-08-12', audience:'All Support', summary:'Record facts, timestamps, indicators, user actions, containment, evidence locations, impact, and requested next action.' },
];

function hdTicket(spec) {
  return {
    id:'', requester:'', department:'', category:'Incident', subcategory:'General',
    priority:'P3', businessImpact:'Single user', assignedTechnician:'Unassigned',
    sla:'2 business days', createdMinutesAgo:30, status:'New', notes:[],
    troubleshootingHistory:[], attachments:[], resolution:'', closureCode:'',
    symptoms:[], logs:[], systemState:[], plausibleCauses:[], correctPath:[],
    hiddenRootCause:'', expectedResolution:'', escalationCriteria:[], correlationKey:'',
    ...spec,
  };
}

const HD_TICKET_TEMPLATES = [
  hdTicket({ id:'HD-2101', requester:'Jordan Bell', department:'Finance', category:'Incident', subcategory:'Account lockout', priority:'P2', businessImpact:'Payroll analyst blocked', sla:'8 hours', createdMinutesAgo:86, description:'My account unlocks, then locks again a few minutes later.', symptoms:['Lockout repeats after successful sign-in','Other Finance users unaffected'], logs:['Event 4740: jbell locked out · caller NS-LT-0117','Task Scheduler: FinanceReportSync last run 08:11'], systemState:['Account enabled','Scheduled task stored credential last changed 90 days ago'], plausibleCauses:['User typing old password','Mobile mail cache','Scheduled task credential'], correctPath:['Verify identity','Trace caller computer','Inspect stored credentials','Correct approved task credential','Unlock once and monitor'], hiddenRootCause:'Scheduled task FinanceReportSync stores the previous password.', expectedResolution:'Update the task through the approved service credential workflow, unlock the account, and verify no new 4740 event.', escalationCriteria:['Unknown lockout source across multiple devices','Signs of credential compromise'] }),
  hdTicket({ id:'SR-2102', requester:'New Hire · Theo Grant', department:'Logistics', category:'Service Request', subcategory:'Onboarding', priority:'P2', businessImpact:'New employee cannot begin work', sla:'4 hours', createdMinutesAgo:112, description:'Create the approved account, access groups, laptop assignment, and warehouse printer.', symptoms:['Manager approval attached','Start date is today'], logs:['HRIS export: employee 8841 active'], systemState:['No AD user exists','Laptop NS-LT-0177 is staged'], plausibleCauses:['Missing approval','Provisioning delay'], correctPath:['Validate approval and identity attributes','Create user in Logistics OU','Apply role groups','Assign endpoint','Verify sign-in and resources'], hiddenRootCause:'Standard approved onboarding request; no technical fault.', expectedResolution:'Complete least-privilege provisioning and document each asset and group assignment.', escalationCriteria:['Requested access exceeds role template','Missing manager or data-owner approval'] }),
  hdTicket({ id:'SR-2103', requester:'HR Operations', department:'Human Resources', category:'Service Request', subcategory:'Offboarding', priority:'P1', businessImpact:'Terminated employee access must end', sla:'15 minutes', createdMinutesAgo:9, description:'Disable Casey Novak immediately per attached termination notice.', symptoms:['Effective time has passed','Laptop return pending'], logs:['HR termination approval HR-8892 attached'], systemState:['Account cnovak enabled','Two active VPN sessions'], plausibleCauses:['Standard request'], correctPath:['Validate authorized notice','Disable account','Revoke sessions','Remove privileged access per runbook','Record asset recovery handoff'], hiddenRootCause:'Authorized urgent offboarding request.', expectedResolution:'Disable access, revoke sessions, preserve mailbox/data per policy, and document asset ownership.', escalationCriteria:['Litigation hold uncertainty','Privileged or service-account dependency'] }),
  hdTicket({ id:'HD-2104', requester:'Priya Shah', department:'Human Resources', category:'Incident', subcategory:'DHCP / connectivity', priority:'P2', businessImpact:'HR employee offline', sla:'8 hours', createdMinutesAgo:63, description:'I am connected to the office network, but nothing opens.', symptoms:['IPv4 address 169.254.44.19','No default gateway'], logs:['ipconfig: DHCP Enabled Yes · Autoconfiguration IPv4 169.254.44.19'], systemState:['Wi-Fi radio enabled','Dock Ethernet adapter reports cable connected','Other floor users online'], plausibleCauses:['DHCP unavailable','VLAN issue','Conflicting adapters'], correctPath:['Recognize APIPA','Isolate network interfaces','Renew lease','Validate IP, gateway, DNS','Test business resource'], hiddenRootCause:'Dock Ethernet adapter is stuck and prevents the active Wi-Fi interface from completing DHCP.', expectedResolution:'Disable the unused dock adapter, renew Wi-Fi, confirm valid lease and resource access.', escalationCriteria:['Multiple clients fail DHCP','Scope exhausted or relay unavailable'] }),
  hdTicket({ id:'HD-2105', requester:'Maya Chen', department:'Operations', category:'Incident', subcategory:'DNS', priority:'P2', businessImpact:'Operations dashboard unavailable', sla:'8 hours', createdMinutesAgo:54, description:'Websites work, but the Operations dashboard says the server cannot be found.', symptoms:['Public internet works','Internal resource opens by IP','Hostname fails'], logs:['Resolve-DnsName opsdash.northstar.example: NXDOMAIN','Client DNS server: 192.0.2.53'], systemState:['VPN connected','Endpoint received public resolver from home router'], plausibleCauses:['Application outage','Routing failure','DNS configuration'], correctPath:['Capture DNS configuration','Query internal name','Compare direct server query','Restore VPN DNS settings','Flush and retest'], hiddenRootCause:'VPN client did not apply the corporate DNS resolver after reconnect.', expectedResolution:'Reconnect/repair the approved VPN profile so corporate DNS is assigned; verify internal hostname resolution.', escalationCriteria:['Internal resolver fails for multiple users','VPN configuration deployment defect'] }),
  hdTicket({ id:'HD-2106', requester:'Elena Ruiz', department:'Logistics', category:'Incident', subcategory:'Printer', priority:'P3', businessImpact:'One warehouse label station delayed', sla:'2 business days', createdMinutesAgo:142, description:'Labels are stuck in the queue and the printer says Ready.', symptoms:['17 jobs remain in Printing','Ping to printer succeeds'], logs:['PrintService 372: driver LabelPro 3.8 terminated unexpectedly'], systemState:['NS-WH-LABEL01 queue Error','NS-PRINT01 spooler degraded'], plausibleCauses:['Out of labels','Network port','Driver crash'], correctPath:['Confirm scope','Preserve jobs','Inspect queue and print-service log','Isolate faulty driver','Apply approved rollback','Test one label'], hiddenRootCause:'LabelPro 3.8 driver crashes the server-side spooler.', expectedResolution:'Roll back to approved driver, restart spooler under change procedure, and verify queued work.', escalationCriteria:['Print-server-wide impact','Driver package unavailable or vendor defect'] }),
  hdTicket({ id:'SR-2107', requester:'Grace Kim', department:'Human Resources', category:'Service Request', subcategory:'Group membership', priority:'P3', businessImpact:'Recruiter cannot upload forms', sla:'2 business days', createdMinutesAgo:188, description:'Approved request: restore contributor access to the HR onboarding folder.', symptoms:['Read access works','Manager approval attached'], logs:['AD group history: removed from GG-HR-Contributors during transfer'], systemState:['Member of GG-HR-Readers','Not member of GG-HR-Contributors'], plausibleCauses:['NTFS ACL issue','Missing group membership'], correctPath:['Validate approval','Add authorized group','Refresh user token','Verify effective access','Document change'], hiddenRootCause:'User was removed from the contributor group during a role transfer.', expectedResolution:'Add GG-HR-Contributors, refresh sign-in token, verify upload, document approval.', escalationCriteria:['No data-owner approval','Requested permission exceeds role'] }),
  hdTicket({ id:'HD-2108', requester:'Amir Patel', department:'Operations', category:'Incident', subcategory:'Group Policy', priority:'P3', businessImpact:'One user lacks mapped drive', sla:'2 business days', createdMinutesAgo:201, description:'My Operations drive disappeared after my laptop was replaced.', symptoms:['Group membership correct','UNC path works manually'], logs:['gpresult: Operations Drive Mapping absent','Computer DN: CN=NS-LT-0145,CN=Computers'], systemState:['User in GG-Operations-Drive','Computer in default Computers container'], plausibleCauses:['Disconnected drive','GPO scope','File server outage'], correctPath:['Verify authorization','Run gpresult','Check computer OU','Move computer through approved admin task','Refresh policy and verify'], hiddenRootCause:'Replacement computer object was never moved into the Operations workstation OU.', expectedResolution:'Move the computer to the correct OU, run policy refresh, verify O: mapping.', escalationCriteria:['GPO link or security filtering change required','Replication/SYSVOL issue'] }),
  hdTicket({ id:'HD-2109', requester:'Noah Williams', department:'Sales', category:'Incident', subcategory:'Windows profile', priority:'P3', businessImpact:'Sales user cannot access normal desktop', sla:'2 business days', createdMinutesAgo:167, description:'Windows signed me into a blank desktop and my shortcuts are missing.', symptoms:['Temporary profile notification','Another user signs in normally'], logs:['User Profile Service 1511: logged on with temporary profile'], systemState:['C:\\Users\\nwilliams exists','Profile registry entry ends in .bak'], plausibleCauses:['Cloud sync issue','Corrupt profile mapping','Malware'], correctPath:['Protect user data','Confirm temporary-profile evidence','Repair or rebuild per runbook','Restore data','Verify sign-in'], hiddenRootCause:'Corrupt ProfileList registry mapping after interrupted update.', expectedResolution:'Repair/rebuild the profile using the approved runbook and verify data and application access.', escalationCriteria:['Encrypted data inaccessible','Repeated corruption or compromise indicators'] }),
  hdTicket({ id:'HD-2110', requester:'Sofia Martin', department:'Operations', category:'Incident', subcategory:'Domain trust', priority:'P2', businessImpact:'Shift supervisor cannot domain sign in', sla:'8 hours', createdMinutesAgo:74, description:'Windows says the trust relationship between this workstation and the domain failed.', symptoms:['Local support account works','Domain sign-in fails'], logs:['Test-ComputerSecureChannel: False','NETLOGON 3210 secure session failed'], systemState:['Computer object enabled','Restored VM snapshot recorded yesterday'], plausibleCauses:['Bad user password','DNS','Machine-account mismatch'], correctPath:['Confirm recovery access','Validate DNS/time/object state','Test secure channel','Repair through approved Tier 2 procedure','Verify sign-in and policy'], hiddenRootCause:'A restored snapshot rolled back the machine-account password.', expectedResolution:'Repair the secure channel, restart if approved, verify domain authentication and gpresult.', escalationCriteria:['Computer object missing or duplicate','Multiple machines lose trust'] }),
  hdTicket({ id:'HD-2111', requester:'Dina Foster', department:'Executive Office', category:'Incident', subcategory:'BitLocker', priority:'P2', businessImpact:'Executive assistant cannot start laptop', sla:'8 hours', createdMinutesAgo:37, description:'The laptop is asking for a BitLocker recovery key after a firmware update.', symptoms:['Recovery screen shows key ID','Device asset tag verified'], logs:['Firmware change CHG-4471 completed overnight'], systemState:['Recovery key escrowed','User identity not yet verified'], plausibleCauses:['Unauthorized tamper','Expected firmware measurement change'], correctPath:['Verify user and device','Match recovery key ID','Provide key through approved secure channel','Boot and validate protection','Document disclosure'], hiddenRootCause:'Approved firmware update changed TPM measurements.', expectedResolution:'Use escrowed recovery key after identity verification, confirm BitLocker returns to Protected.', escalationCriteria:['Key unavailable or mismatch','Unapproved firmware change or tamper concern'] }),
  hdTicket({ id:'HD-2112', requester:'IT Monitoring', department:'Information Technology', category:'Incident', subcategory:'Windows service', priority:'P2', businessImpact:'Department print service degraded', sla:'8 hours', createdMinutesAgo:48, description:'Print Spooler stops immediately after it starts on NS-PRINT01.', symptoms:['Service exit code 1067','Issue began after driver package'], logs:['System 7031: Print Spooler terminated unexpectedly','PrintService 808: LabelPro provider fault'], systemState:['Server reachable','Other services healthy'], plausibleCauses:['Service account','Dependency','Faulty driver'], correctPath:['Preserve logs','Check dependency and recent change','Quarantine faulty driver','Use approved rollback','Restart and validate queues'], hiddenRootCause:'Third-party label driver crashes the spooler.', expectedResolution:'Rollback the driver under change control and verify all queues.', escalationCriteria:['Production reboot required','Vendor package or server-wide outage'] }),
  hdTicket({ id:'HD-2113', requester:'Remote Employee · Kai Ross', department:'Sales', category:'Incident', subcategory:'VPN', priority:'P2', businessImpact:'Remote seller cannot reach internal apps', sla:'8 hours', createdMinutesAgo:95, description:'VPN accepts MFA, connects for a few seconds, then disconnects.', symptoms:['Internet access stable','MFA succeeds'], logs:['VPN client: certificate validation failed · NotAfter 2026-08-16'], systemState:['User certificate valid','Gateway certificate expired'], plausibleCauses:['Password','Home firewall','Gateway certificate'], correctPath:['Capture client log and time','Validate certificate chain and expiry','Correlate other users','Escalate gateway certificate renewal','Communicate workaround only if approved'], hiddenRootCause:'VPN gateway certificate expired.', expectedResolution:'Escalate as shared service incident for approved certificate renewal; validate new chain.', escalationCriteria:['Always: production gateway certificate change required'] }),
  hdTicket({ id:'SEC-2114', requester:'Luis Ortega', department:'Sales', category:'Security Incident', subcategory:'Phishing', priority:'P1', businessImpact:'Possible credential compromise', sla:'15 minutes', createdMinutesAgo:7, description:'I clicked a shipping link and signed in again. Was that real?', symptoms:['Lookalike domain','Unexpected sign-in page'], logs:['Browser history: northstar-shipping.example-login.test','Identity log: unfamiliar sign-in pending review'], systemState:['Email preserved','Endpoint protection has no malware verdict'], plausibleCauses:['Benign vendor portal','Credential phishing'], correctPath:['Verify reporter','Preserve email/URL/time','Protect account within procedure','Escalate immediately','Do not declare endpoint safe'], hiddenRootCause:'Credential-phishing page captured the password.', expectedResolution:'Escalate to cybersecurity, revoke sessions/reset credential per response runbook, preserve evidence.', escalationCriteria:['Always: potential credential compromise'] }),
  hdTicket({ id:'SEC-2115', requester:'Endpoint Security', department:'Cybersecurity', category:'Security Incident', subcategory:'Malware alert', priority:'P1', businessImpact:'Potential endpoint compromise', sla:'15 minutes', createdMinutesAgo:12, description:'High-confidence malware alert on NS-LT-0162 requires help desk contact and containment coordination.', symptoms:['User reports browser pop-ups','EDR alert high confidence'], logs:['EDR: suspicious powershell child of browser','SHA256 aaa... training fixture'], systemState:['Device online','Isolation pending security approval'], plausibleCauses:['Malicious extension','False positive'], correctPath:['Do not delete evidence','Confirm user/device','Coordinate containment','Record observations','Warm handoff to security'], hiddenRootCause:'Malicious browser extension launched an encoded PowerShell command.', expectedResolution:'Security-led containment and investigation; help desk handles user communication and replacement device.', escalationCriteria:['Always: confirmed or suspected malware'] }),
  hdTicket({ id:'SR-2116', requester:'Dina Foster', department:'Executive Office', category:'Service Request', subcategory:'Software installation', priority:'P2', businessImpact:'Board materials due tomorrow', sla:'8 hours', createdMinutesAgo:126, description:'Install the approved PDF editor before tomorrow morning.', symptoms:['Manager approval attached','License available'], logs:['Software catalog: PDF Studio Enterprise · Approved'], systemState:['Device compliant','Package available in endpoint manager'], plausibleCauses:['Standard request'], correctPath:['Validate approval/license/device','Deploy approved package','Verify launch and license','Document'], hiddenRootCause:'No fault; fulfilled standard request.', expectedResolution:'Install from managed catalog and verify with user.', escalationCriteria:['Unapproved software or elevated exception requested'] }),
  hdTicket({ id:'HD-2117', requester:'Monitoring', department:'Information Technology', category:'Incident', subcategory:'Disk space', priority:'P2', businessImpact:'File server may stop accepting data', sla:'8 hours', createdMinutesAgo:41, description:'NS-FILE01 data volume has 4% free space.', symptoms:['Growth accelerated this morning','Finance archive share largest'], logs:['Get-Volume D: SizeRemaining 81GB of 2TB','Top path: D:\\Shares\\Finance\\Exports'], systemState:['Nightly export job created duplicate output','Backups healthy'], plausibleCauses:['Normal growth','Log growth','Duplicate export'], correctPath:['Confirm impact and growth','Identify safe cleanup candidates','Preserve business data','Stop duplicate generation through owner','Use approved cleanup/change'], hiddenRootCause:'Finance export job wrote duplicate archives after a retry loop.', expectedResolution:'Stop duplicate job via app owner, remove duplicates after approval, verify free-space threshold and monitoring.', escalationCriteria:['Storage expansion or production job change required'] }),
  hdTicket({ id:'HD-2118', requester:'Evan Parker', department:'Finance', category:'Incident', subcategory:'File permissions', priority:'P2', businessImpact:'Payroll file cannot be updated', sla:'8 hours', createdMinutesAgo:58, description:'I can open the payroll workbook but cannot save changes.', symptoms:['Read succeeds','Modify denied in Payroll subfolder'], logs:['Effective access: Read & Execute','Share permission: Change'], systemState:['User in GG-Finance-Users','Missing GG-Finance-Contributors'], plausibleCauses:['File locked','NTFS permission','Share offline'], correctPath:['Validate requested access','Calculate group-based effective access','Check share and NTFS','Correct approved membership','Refresh token and verify'], hiddenRootCause:'User is missing the NTFS contributor group.', expectedResolution:'Restore approved contributor group and verify Modify without direct user ACL.', escalationCriteria:['No data-owner approval','Explicit deny or ACL redesign required'] }),
  ...['Maya Chen|Operations','Elena Ruiz|Logistics','Noah Williams|Sales','Priya Shah|Human Resources','Evan Parker|Finance'].map((row, index) => {
    const [requester, department] = row.split('|');
    return hdTicket({ id:`HD-${2119 + index}`, requester, department, category:'Incident', subcategory:'Enterprise application', priority:index === 0 ? 'P2' : 'P3', businessImpact:'Purchasing application unavailable', sla:index === 0 ? '8 hours' : '2 business days', createdMinutesAgo:32 - index * 4, description:'Purchasing opens, but sign-in ends with a secure connection error.', symptoms:['Same application error','Other websites and file shares work'], logs:['Browser: NET::ERR_CERT_DATE_INVALID','TLS NotAfter: 2026-08-16T23:59:59Z'], systemState:['NS-APP01 online','Application service running'], plausibleCauses:['User account','Browser cache','Application certificate'], correctPath:['Confirm shared symptom','Compare timestamps and error','Link related incidents','Validate certificate evidence','Escalate controlled renewal'], hiddenRootCause:'NS-APP01 service certificate expired.', expectedResolution:'Link to the common incident/problem, renew the certificate through change control, verify all user paths.', escalationCriteria:['Always: shared production application and certificate change'], correlationKey:'APP-CERT-EXPIRY-01' });
  }),
];
